[phases.setup]
aptPkgs = ["..."]

[phases.install]
cmds = ["cd frontend && npm install"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd api && gunicorn entrypoint:app --bind 0.0.0.0:$PORT"