[build]
builder = "nixpacks"
watchPatterns = ["api/**", "frontend/**"]

[deploy]
startCommand = "cd api && gunicorn entrypoint:app"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"